### ISSUE TITLE
Tests are broken due to recent SDK changes

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php-contrib#19]
**Steps to reproduce**
make test

**What is the expected behavior?**
Errors: 0

**What is the actual behavior?**
Errors: 21

**Comment by Blacksmoke16** [comment]
```sh
Time: 00:00.405, Memory: 24.00 MB

OK (410 tests, 1034 assertions)
```

Can you share an example of what one of the errors is?

**Comment by tidal** [comment]
As far as I have seen this is all AWS related code, because there is nothing much else yet anyway.
My guess is that said code runs against the 0.0.3 release of the SDK, while the [composer ](https://github.com/open-telemetry/opentelemetry-php-contrib/blob/main/composer.json#L15) pulls dev-main.

A temporary solution might be to require SDK 0.0.3 for the main branch. 
However the Symfony Bundle will be based on the latest SDK version in dev-main, so in both cases I will not be able create a PR for the Bundle until the tests pass against current SDK dev-main.
