### ISSUE TITLE
Register opentelemetry-php-contrib package on packagist.org

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php-contrib#21]
**Is your feature request related to a problem?**

`open-telemetry/opentelemetry-php-contrib` composer package is not installable without referencing the vcs repository in `composer.json` like that:
```
[...]
"repositories": [
        {
          "type": "vcs",
          "url": "https://github.com/open-telemetry/opentelemetry-php-contrib"
        }
 ],
[...]
```

**Describe the solution you'd like**

One of the code owners registers the package on [`packagist.org`](https://packagist.org/)

**Describe alternatives you've considered**

Package users have to reference the repository in `composer.json`. (see above)

**Comment by tidal** [comment]
@Blacksmoke16 
Thank you! Interesting article. 
I have used splish some years ago for another project after watching [this talk](https://www.youtube.com/watch?v=ZVsDA6GhKOU) by "Mr. Symfony" himself. However it was a bit difficult to setup with CI back then.

The plan is defenitly to create separate packages. And I'm about to make everything work in this [org](https://github.com/otel-php), so that packagist can grab the sources from the mirrors which will be there.

A while ago I also created a test org to test different solutions:
https://github.com/php-monorepo-test

One solution I tested is "[GIT SUBTREE SPLIT AS A SERVICE](https://www.subtreesplit.com/)", which internally uses splish as well.
It's super easy to setup and works like a charm. Only tags are not pushed to the mirrors, but this can be fixed, and back then I could not check, if it works with opentelemtry's restrictions to repos. But now that I can check, I will do.

The other solution I tested is [symplify/monorepo-split-github-action](https://github.com/symplify/monorepo-split-github-action). I could not get it to work, and I don't know if I'm the problem or the github-action.
However I also tested [symplify/monorepo-builder](https://github.com/symplify/monorepo-builder) from the same authors wich works fine. It provides tools around monorepos/subtrees especially for PHP, like merging and synching composer.json etc.

There is another github action which I want to check, and lastly I want this to be as automated as possible. So the dream would be a merged PR with a new package would automatically result in a mirror repo being setup and configured. 
Let's see, but the separate packages will come by any means!

**Comment by dkarlovi** [comment]
IMO you can register this whole package on Packagist, but in general the preferred usage should be through split packages.

These are examples how the split can be done:

Gitsplit config
https://github.com/sigwinhq/xezilaires-dev/blob/master/.gitsplit.yml

GH action config
https://github.com/sigwinhq/xezilaires-dev/blob/master/.github/workflows/gitsplit.yaml

GH action runs:
https://github.com/sigwinhq/xezilaires-dev/actions/workflows/gitsplit.yaml

You need to define a repository secret called `GITSPLIT_TOKEN` in the [Action secrets](https://github.com/open-telemetry/opentelemetry-php-contrib/settings/secrets/actions) and have permissions to push into remote repos, this is enough for this to work.

**Comment by dkarlovi** [comment]
Note: I'm actually not sure having a "contrib" repo is even worth it if you end up splitting stuff out of it anyway. If it was me, I'd keep everything in the original repo and can then split as many packages as I like from there.

**Comment by tidal** [comment]
Closing this.
The repo has been added to packagist (Just for development puposes)

A ticket regarding separate packages has been created at the main libraries repo: https://github.com/open-telemetry/opentelemetry-php/issues/507
